### ISSUE TITLE
sudo make install - TODO: install target

### ISSUE THREAD

**Issue by smcallister594** [certnanny/sscep#102]
Hey

somewhat new to linux but got a project to configure 400> rasp-pis so they can enroll and auto renew against our CA. 

I've got as far as make install when i get the following
```pi@raspberrypi:/usr/local/src/sscep $ sudo make install
echo "TODO: install target"
TODO: install target
```
From what a colleague has advised, I shouldn't really have to specify an install target. 

Is this what's being asked for here? If so what should I be specifying? Or am I totally wrong? 

```pi@raspberrypi:/usr/local/src/sscep $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by smcallister594** [comment]
fixed it

```sudo make all OPENSSL=/usr/lib/arm-linux-gnueabihf
sudo cp sscep_dyn /usr/local/bin
ln -s /usr/local/bin/sscep_dyn /usr/local/bin/sscep```

**Comment by gotthardp** [comment]
Thanks for the workaround.
We have migrated to GNU autotools recently, so even the 'make install' works now.
