### ISSUE TITLE
Interoperate with Redwax Server at https://interop.redwax.eu/rs/scep/

### ISSUE THREAD

**Issue by minfrin** [certnanny/sscep#104]
Interoperate with the demo server for Redwax at https://interop.redwax.eu/rs/scep/.

https://github.com/certnanny/sscep/pull/103 is required to connect.

**Comment by gotthardp** [comment]
Hello, I just merged the #103. Could you please build the **develop** branch and check if it works now?

**Comment by gotthardp** [comment]
I just tried `sscep getca -u http://interop.redwax.eu/test/simple/scep -c redwax` and it works, so I guess everything is OK. If not, please open a new issue.
