### ISSUE TITLE
GetCert/GetCRL encode IssuerAndSerialNumber incorrectly

### ISSUE THREAD

**Issue by ovk** [certnanny/sscep#106]
It looks like commit 88df41d669ee025deeff78693dd22cf6c5a6de0c broke encoding of `IssuerAndSerialNumber `.

The `PKCS7_ISSUER_AND_SERIAL_print_ctx` macro as you see used here https://github.com/certnanny/sscep/blob/master/pkcs7.c#L112 produces human-readable ASCII string and not proper ASN1 representation of the `IssuerAndSerialNumber`.

**Comment by oliwel** [comment]
We had a similar problem on the ML last week which was "resolved" by recompiling, have a a look at 
https://sourceforge.net/p/openxpki/mailman/message/36948547/

**Comment by ovk** [comment]
Obviously recompiling doesn't work for me, but patching the code I linked to encode IssuerAndSerialNumber  properly does.

**Comment by oliwel** [comment]
A pull request would be  gratefully appreciated ;)

**Comment by ovk** [comment]
Will do

**Comment by gotthardp** [comment]
I merged the fix to the `develop` branch with cbbc0ef5d580dd88bc65d9c6aea6c28b008eca42. It would be great if you could check the problem has disappeared now.

**Comment by ovk** [comment]
@gotthardp I tested GetCert using latest `develop` branch and it immediately crashed. After some debugging turns out the crash is unrelated, and is caused by the uninitialized `bn` variable here https://github.com/certnanny/sscep/blob/403603a3311a7b04e5c6199c15d33d5b2f1b29c5/src/sscep.c#L931

After initializing it to `NULL` like so: `BIGNUM *bn = NULL;` (this is what `BN_dec2bn` expects as per documentation) the `GetCert` worked and my test server was able to parse it and respond.

**Comment by gotthardp** [comment]
Thank you for your effort, @ovk! I will commit the fix tomorrow after I do few more tests.
