### ISSUE TITLE
Re-ordering "Issuer" and "Subject" in IssuerAndSubject.

### ISSUE THREAD

**Issue by tedescn** [certnanny/sscep#108]
See attached *.diff file that re-orders Issuer and Subject within ias.c 

In conjunction with #107, this addresses CertInitial messages issues on the Verisign/Symantec/DigiCert Managed PKI platforms.

This is similar to #52, that addresses the issue identified in #42.

[ias.c.diff.txt](https://github.com/certnanny/sscep/files/4533849/ias.c.diff.txt)
Regards
Nigel

**Comment by gotthardp** [comment]
The patch looks reasonable. I integrated it to the `develop` branch.
