### ISSUE TITLE
SHA256 support

### ISSUE THREAD

**Issue by juresaht2** [certnanny/sscep#116]
Hello,

This is a feature request. I would like to ask that SHA256 support be added to SSCEP, since SHA-1 is deprecated since 2017 and can no longer be used for web SSL certificates.

This page contains instructions how the source code can be modified to add support for SHA256 and SHA512:
https://www.dogtagpki.org/wiki/SCEP_in_Dogtag

For my project I had preformed these changes on the latest version and confirm that they work. I am contributing the modified source code in the form of a compatible fork:
https://github.com/juresaht2/sscep/commit/19dfffeccc343daf35016d50c6655084c4fcd0af

I have not provided this in the form of a merge request, because while the modified code works, I do not believe it is suitable for merging, as signature verification which no longer works is simply disabled:
https://github.com/juresaht2/sscep/blob/master/pkcs7.c#L420

Hopefully the modified code is still useful.

LP,
Jure
T-2 d.o.o.

**Comment by kuromike0629** [comment]
+1

**Comment by gotthardp** [comment]
Hello. I at least started: the changes to sscep.c were included in some ancient pull request, which got integrated in to the `develop` branch with 23e306f90cbe262d3bc4e485479a50873b3983b8. The rest of the changes is still pending though. Contibutions (to the `develop` branch) are welcome.

**Comment by gotthardp** [comment]
The documentation is also fixed now. Feel free to open another specific issue if you are missing some additional feature.
