### ISSUE TITLE
Unmerged pull requests and unclear baseline for further development

### ISSUE THREAD

**Issue by gotthardp** [certnanny/sscep#118]
Hello. I saw (here https://github.com/certnanny/sscep/issues/111) that some alignment on sscep further maintenance has been done, but the activity ceased somehow again. Some work on cmake and overall restructuring is done here https://github.com/m-seker/sscep, but the old PR has not been included. Cherrypicking the PR’s will not be possible after integrating the cmake work back to master. It would be pity to lose them all!

Would it be possible (and I volunteer to help, if needed) to create a development branch here(!), merge all PR's that appear to look right, quickly re-do the restructuring from https://github.com/m-seker/sscep and then have here a baseline for further development and testing by the community?
Given the amount of pending changes and diverged forks at various locations I am not sure which is the stable code base to use for testing and further enhancements.

**Comment by tedescn** [comment]
While I may not be able to help merge the PR. Where possible, I'm more than happy to support testing.

**Comment by mbartosch** [comment]
@gotthardp if you are willing to help with maintenance of this project (I understood you are volunteering) please get in touch with me via one of the channels mentioned in https://github.com/certnanny/sscep/issues/111#issuecomment-675489979
I agree that it is useful to keep this repository for the main work on the project, so I think the best way forward might be for you to be added to the project team so you can help @m-seker maintaining the project.

**Comment by mbartosch** [comment]
@tedescn the same applies to you, of course...

**Comment by gotthardp** [comment]
Vast majority of the pull requests is merged now in the `develop` branch. Now we should re-test the functionality.
