### ISSUE TITLE
enroll without private key

### ISSUE THREAD

**Issue by cs520** [certnanny/sscep#12]
I'm trying to use sscep to sign certs from a Microsoft CA with NDES. I just want to send the CSR to the CA and get a signed cert. The enroll operation requires a -k parameter for the private key, but the sscep caller does not have access to the private key corresponding to the public key in the CSR. Is there a way to get the cert signed without the private key? Thank you.

**Comment by mbartosch** [comment]
My understanding of the SCEP draft is that this is not possible.

**Comment by willsheppard** [comment]
Try giving the encrypted private key as value to -k, then arrange for sscep to perform the operation with NDES.
