### ISSUE TITLE
Certificate renewal against NDES with Standalone CA

### ISSUE THREAD

**Issue by chrust** [certnanny/sscep#123]
Has anyone succeed to do a certificate renewal using a previously issued certificate to validate the new certificate request? The target NDES(scep server) is running on ws2019 with a Standalone CA on it.
I followed these instructions but with no luck. sscep reports illegal payload size and server logs Event ID 28.

[link1](https://social.technet.microsoft.com/wiki/contents/articles/9063.active-directory-certificate-services-ad-cs-network-device-enrollment-service-ndes.aspx#Certificate_Renewal) 
[link2](https://docs.microsoft.com/sv-se/archive/blogs/jeffbutte/236)
[link3](https://social.technet.microsoft.com/Forums/office/en-US/a2a8fb0a-46be-4ec1-9ead-04483f4ae618/ndes-automated-renewal-of-existing-certificate-via-scep-not-working?forum=winserversecurity)

Note: It might well be that the issue lays on server side...

**Comment by mbartosch** [comment]
Hi,

> Has anyone succeed to do a certificate renewal using a previously issued certificate to validate the new certificate request? The target NDES(scep server) is running on ws2019 with a Standalone CA on it.
> I followed these instructions but with no luck. sscep reports illegal payload size and server logs Event ID 28.

sscep is absolutely capable of doing so, and it works without problems with the OpenXPKI SCEP server (actually, -K and -O were implemented for exactly this purpose back in 2007).

I've never used sscep in conjunction with Microsoft NDES, though.

Cheers

Martin

**Comment by tedescn** [comment]
While I don't use NDES, I also cannot support this feature. Please remember the NDES SCEP Responder must include a corresponding and support configuration of this client. 

The 3 configuration options are indicated within https://tools.ietf.org/html/rfc8894 Section 2.3 - the trick is likely to ensure the NDES config supports? It might be worth checking you NDES logs? I would look in detail at the received csr, is it compliant? Note I'm no NDES expert!

While this isn't a feature I use today, I can imagine why I would want this.

Regards
Nigel

**Comment by chrust** [comment]
Just a quick update. Since my last post I tried sscep against the Enterprise CA and it works fine. So it might be that the problem lays on the server side. I will close this issue.
