### ISSUE TITLE
Error PKG_CHECK_MODULES(openssl, openssl >= 0.9.7)

### ISSUE THREAD

**Issue by Faizan680** [certnanny/sscep#127]
on running configure file after building it from bootstrap.sh getting error on PKG_CHECK_MODULES.
Building it on ubuntu 18.04

admin1@nso-1728-171:~/sscep$ openssl version
OpenSSL 1.1.1  11 Sep 2018

Error:

checking dependency style of gcc... (cached) gcc3
./configure: line 12785: syntax error near unexpected token `openssl,'
./configure: line 12785: `PKG_CHECK_MODULES(openssl, openssl >= 0.9.7)'

Plz suggest the steps to compile and build sscep on the ubuntu machine. I am using the master branch

**Comment by gotthardp** [comment]
Do you have `pkg-config` installed? looks like the `PKG_CHECK_MODULES` macro is missing.

**Comment by Faizan680** [comment]
Thanks, Petr Gotthard for the quick answer, installing pkg-config fix the issue. appreciate the help.

**Comment by Faizan680** [comment]
-
