### ISSUE TITLE
Does SSCEP enroll works with RA?

### ISSUE THREAD

**Issue by rfrandsen** [certnanny/sscep#140]
I did a test to use SCEP with CA and it is working perfectly. I am now trying to enroll a certificate throught a RA, and having a error. 
Is it compatible or was it tested?

___________________________________________________________________________

THE LOGS IN MY RA: 
Nov 11 2021 11:36:31.583: CRYPTO_PKI_SCEP: CS received GetCACaps request
Nov 11 2021 11:36:31.583: CRYPTO_PKI_SCEP: CA sending list of capabilites (GetNextCACert Renewal SHA2 hashes)
Nov 11 2021 11:36:31.588: CRYPTO_CS: Capabilities sent
Nov 11 2021 11:36:31.625: CRYPTO_PKI_SCEP: CS received PKIOperation request
Nov 11 2021 11:36:31.625: CRYPTO_CS: processing SCEP request, 3787 bytes
Nov 11 2021 11:36:31.625: CRYPTO_CS: read SCEP: registered and bound service SCEP_READ_DB_139
Nov 11 2021 11:36:31.626:  CRYPTO_PKI: Deleting cached key having key id 171
Nov 11 2021 11:36:31.626:  CRYPTO_PKI: Attempting to insert the peer's public key into cache
Nov 11 2021 11:36:31.626:  CRYPTO_PKI:Peer's public inserted successfully with key id 172
Nov 11 2021 11:36:31.627:  CRYPTO_PKI: Expiring peer's cached key with key id 172
Nov 11 2021 11:36:31.627: CRYPTO_CS: scep msg type - 19
Nov 11 2021 11:36:31.627: CRYPTO_CS: trans id - FCEB8A823C56B42C7CDCFDF49E8D3C14
Nov 11 2021 11:36:31.644: CRYPTO_CS: read SCEP: unregistered and unbound service SCEP_READ_DB_139
Nov 11 2021 11:36:31.644: CRYPTO_PKI_SCEP: Received message is PKCSReq
Nov 11 2021 11:36:31.644: CRYPTO_CS: received an enrollment request
Nov 11 2021 11:36:31.644: CRYPTO_CS: Enrollment request cannot be found in erdbase corresponding to trans id FCEB8A823C56B42C7CDCFDF49E8D3C14
Nov 11 2021 11:36:31.644: CRYPTO_CS: Enrollment password (challenge) obtained from pkcs10 message is
Nov 11 2021 11:36:31.644: CRYPTO_CS: Enrollment request cannot be found in erdbase corresponding to enrollment password
Nov 11 2021 11:36:31.644: CRYPTO_PKI: creating trustpoint clone UTILITY_RA1
Nov 11 2021 11:36:31.644: CRYPTO_CS: cert which signed the enrollment request is not an RA cert
Nov 11 2021 11:36:31.644:  CRYPTO_PKI: Deleting cached key having key id 172
Nov 11 2021 11:36:31.644:  CRYPTO_PKI: Attempting to insert the peer's public key into cache
Nov 11 2021 11:36:31.644:  CRYPTO_PKI:Peer's public inserted successfully with key id 173
Nov 11 2021 11:36:31.645:  CRYPTO_PKI: Expiring peer's cached key with key id 173
Nov 11 2021 11:36:31.645: CRYPTO_CS: checking policy for enrollment request ID=1
Nov 11 2021 11:36:31.645: CRYPTO_CS: request has been authorized, transaction id=FCEB8A823C56B42C7CDCFDF49E8D3C14
Nov 11 2021 11:36:31.645: CRYPTO_CS: locking the CS
Nov 11 2021 11:36:31.645: CRYPTO_CS: cannot find key usage extension in PKCS#10
Nov 11 2021 11:36:31.645: CRYPTO_CS: failed to get fields from PKCS10
Nov 11 2021 11:36:31.645: CRYPTO_CS: unlocking the CS
Nov 11 2021 11:36:31.645: CRYPTO_CS: failed to write SCEP response
Nov 11 2021 11:36:31.645: CRYPTO_CS: removing trustpoint clone UTILITY_RA1

**Comment by gotthardp** [comment]
Hello. Would you please share what was the issue? Just in case somebody else has a similar problem.
