### ISSUE TITLE
Sscep version compatible with openssl 3.0.2 15

### ISSUE THREAD

**Issue by ishackigozi** [certnanny/sscep#150]
Hello,
I am trying to compile version 0.10.0 on Ubuntu 22.04 LTS. OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022) and am getting this error. 

![image](https://user-images.githubusercontent.com/64915345/173656993-3cb0b5b5-63dc-41ef-ad05-ef7c4582ca5d.png)

checking dependency style of gcc... (cached) gcc3
./configure: line 13520: syntax error near unexpected token `openssl,'
./configure: line 13520: `PKG_CHECK_MODULES(openssl, openssl >= 1.1.0)'
root@SRA1500003120:~/sscep_dir/sscep-0.10.0# ./configure > output
./configure: line 13520: syntax error near unexpected token `openssl,'
./configure: line 13520: `PKG_CHECK_MODULES(openssl, openssl >= 1.1.0)

**Comment by ishackigozi** [comment]
Thanks for the information, I have installed pkg-config. 

Although, I am not having this issue.

![image](https://user-images.githubusercontent.com/64915345/173659561-8960e085-9020-43ae-a89e-75eb5c4ab682.png)


configure: error: Package requirements (openssl >= 1.1.0) were not met:

No package 'openssl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables openssl_CFLAGS
and openssl_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by gotthardp** [comment]
I guess the error *No package 'openssl' found* is pretty obvious, right? That's another missing dependency.

**Comment by ishackigozi** [comment]
Please ignore, thank you for your help. I installed libssl-dev and everything works.

**Comment by ishackigozi** [comment]
Thank you @gotthardp
