### ISSUE TITLE
sscep getcert options not clear

### ISSUE THREAD

**Issue by mrscotty** [certnanny/sscep#17]
The options for the getcert operation are not clear. Here is an excerpt of the options for both getcert and enroll, with my comments in square brackets.

OPTIONS for getcert:

  -l <file>  Local certificate file [signature certificate for SCEP request]
  -w <file> Write certificate in file [destination for received cert]

Options for enroll:

  -l <file> Write enrolled certificate in file [destination of received cert]
  -O <file> Signature certificate (used instead of self-signed) [signature certificate for SCEP request]

If the opts can't be changed due to backwards compatibility, at least the README should be updated to clarify that the '-l' option for getcert is the signature certificate for the SCEP request.

**Comment by gotthardp** [comment]
The README was updated. Let's not modify the opts for now.
