### ISSUE TITLE
Request PQ Dilithium5 Cert with SSCEP

### ISSUE THREAD

**Issue by scottthomas007** [certnanny/sscep#170]
Bonjour,

I am requesting a PQ (Dilithium5) certificate with sscep but having following error:

140279423861952:error:0609E09C:digital envelope routines:pkey_set_type:**unsupported algorithm**:../crypto/evp/p_lib.c:210:
140279423861952:error:0606F076:digital envelope routines:EVP_PKCS82PKEY:**unsupported private key algorithm:**../crypto/evp/evp_pkey.c:36:TYPE=1.3.6.1.4.1.2.267.7.8.7
140279423861952:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:

I have also replaced the legacy openssl with PQOpenSSL (**OpenSSL 1.1.1u  30 May 2023, Open Quantum Safe 2023-05**)

Please guide me

**Comment by mbartosch** [comment]
The sscep code base compiles against upstream OpenSSL and hence does not support the unofficial PQC OpenSSL variant published by Open Quantum Safe.
First of all, the PQC standardization is by far not finished yet. Although we now have the finalists which will very likely be adopted in the upcoming standards, it is not clear yet how these algorithms will be included in all the standards which deal with cryptographic algorithms. We even do not know yet if PQC algorithms will simply replace traditional algorithms in certificates and other primitives (this is what Open Quantum Safe's OpenSSL is doing) or the IETF will propose a hybrid approach to allow for a smooth transition between traditional and PQC algorithms. I believe the latter will be the way to go, but for that, as mentioned, we first need standardization to define how hybrid algorithms shall be encoded/transported and how they shall be used in existing standards. In my opinion it does not make much sense to prepare for the native replacement of traditional algorithms with PQC ones before standardization has finished.

That said, even if sscep already supported PQC algorithms via the OQS OpenSSL fork, it is very likely that this will not be the final word on it, and it is even more likely that all the other infrastructure involved (software used by the Issuing CA, Relying Parties and End Entities) will not support these PQC algorithms right now.

For the sscep project, the sensible way to deal with this is to wait for standardization to finish (algorithm choice, updates of the X.509, PKCS#7 and SCEP RFCs) and only then implement the necessary modifications.
