### ISSUE TITLE
how to get the certificates chain in the sscep enroll request

### ISSUE THREAD

**Issue by nagendransundaram** [certnanny/sscep#176]
scep enroll request responded with certificate chain, but the -l output cert has only one certificate. The chain is missing. Is there anyway to get the entire cert chain

./sscep enroll -u http://example.com/scep -c ca.crt -k local.key -r local.csr -l local.crt

**Comment by mbartosch** [comment]
According to [the SCEP standard](https://www.rfc-editor.org/rfc/rfc8894.html#name-certrep-success) the SUCCESS PKIMessage contains the end entity certificate and optionally _may_ include additional certificates.
sscep only exports the end entity certificate, via the -l option.
The certificate chain for the EE certificate can be constructed from the delivered end entity certificate and building the certificate chain using the certificates delivered by the SCEP GetCACert operation.
