### ISSUE TITLE
PKCS7_RECIP_INFO_set:encryption not supported for this key type

### ISSUE THREAD

**Issue by LkZtCode** [certnanny/sscep#177]
this ca.cert is
-----BEGIN CERTIFICATE-----
MIIDEjCB+6ADAgECAhRwlrOqr9rrlUFHrAGE3/VOmeIUfTANBgkqhkiG9w0BAQsF
ADA1MSYwJAYDVQQDDB1PcGVuUEtJIERlZmF1bHQgUlNBIFJvb3RDQSBWMTELMAkG
A1UEBhMCQ04wHhcNMjMwNTI0MDkxNTUzWhcNMjUwNTIzMDkxNTUzWjAdMRswGQYD
VQQDDBJUZXN0IEhTTSBTdWJDQSAwMDEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAR2rFDzBP0smdFsz0dMyzFLl5Cum00m1AJ7RXFD1HjKYrTK5RqcjAhzWT+9ZTwk
sHcJIOjawl/UNmwpwOssxwNtMA0GCSqGSIb3DQEBCwUAA4ICAQC5bALgJLkAirvh
pwzKsMlqPkRBHom47fXgFg182rgdS3Ov3bPtoGX5yFaJVXyLmfX0KPXoUzQ6RLCf
i0vSpdrhPGjtkN0zNxTsuJEKYjokF8kHoM1wIzlGBaaX2Bg8+wI8dUqjLC2UbeIN
6rdWQcR8TcSSvQgywOf0JRogYKIsMMY9DZrGOXr6RU5MIf1ycJVoOhPfKa+Omfx3
51W5esmXSEJfqILwzOfeX26sX1YV5fCI+l2VxFmicYv4oPN39onHDKMnTyd8r2kB
KMc8fZdpT1ei0+/znlC+I4lJV+D3qmUpbzGNRNJm0ZMyIGzlR1vB057+vtGwusan
p4n/JJV5Rx7+Gm/UHieQtkQMa9GLjawaqrWt/stUvrgL9xy29iXUbi/8uN4AyVXR
MhE/b/xe77uiffhqkE+DdcHTaJAnDUaljECFCFP/4s1HUvggqR1GZnXfo6IDHfnT
KIkDChpB47k8rXh6XKs5yEhW9a+UQWEolDwzDnFAWjOCXfW9gxJl60MSt5wrWIYf
h2c2VpM3OaYyYpUckvzjCgmKpfB49ODYifEEk9i/th7fzfR3xq7FfRsC8NltORFX
z32pEEcD0e01/KsZc5A+WjgwnmkwrxLP0idI3YF4t2qjuwkHplLTNJ/cmYHavdH5
0CaC1DedejKlF7C+MwVfHg6GsngUaw==
-----END CERTIFICATE-----

this request.cnf is 
id_section        = new_oids

[ req ]
default_bits       = 2048
default_keyfile    = local.key
encrypt_key        = no

distinguished_name = req_dn
attributes         = req_attributes
req_extensions     = req_ext

[ new_oids ]
certTemplateName   = 1.3.6.1.4.1.311.20.2

[ req_dn ]
0.domainComponent  = org
1.domainComponent  = OpenXPKI
2.domainComponent  = Test Deployment
commonName         = device

[ req_attributes ]

[ req_ext ]
basicConstraints   = critical, CA:FALSE
keyUsage           = critical, digitalSignature, keyEncipherment
extendedKeyUsage   = serverAuth, clientAuth
subjectAltName     = @alt_names
certTemplateName   = ASN1:UTF8String:pc-client

[ alt_names ]
DNS.1 = www.example.com
DNS.2 = example.com

excute sscep enroll -u http://10.13.0.185:9000/api/v2/scep/88_fUyKwHiPsjrT/cgi-bin/pkiclient.exe -c ca.crt-0 -k local.key -r local.csr -l local.crt

sscep: sending certificate request
sscep: request payload encrypt failed
20B03899FFFF0000:error:10800096:PKCS7 routines:PKCS7_RECIP_INFO_set:encryption not supported for this key type:../crypto/pkcs7/pk7_lib.c:645:
20B03899FFFF0000:error:10800078:PKCS7 routines:PKCS7_encrypt_ex:error adding recipient:../crypto/pkcs7/pk7_smime.c:469:

**Comment by mbartosch** [comment]
The error message is accurate.

Elliptic Curve certificates are not suitable for encryption (which is required for the SCEP protocol to work).
