### ISSUE TITLE
Documentation Discrepeancy

### ISSUE THREAD

**Issue by Flyslinger2** [certnanny/sscep#179]
In your instructions:

GetCertFile 	Write certificate asquired via getcert operation. 	./cert.crt 	-w

<snip>

GetCrlFile 	Write CRL to file. 	./crl.crl 	-w

============================================================
How can both be "-w"?

**Comment by mbartosch** [comment]
sscep follows the decades long conventions Unix users are familiar with and which are adopted throughout the entire Unix command line tool ecosystem.
Re-using a common option such as -w OUTFILE for file name specification of an output file across different operation modes of a command line tool is very common in the Unix environment and will be expected by experienced users.

Hence, works as designed.
