### ISSUE TITLE
How to revoke/unenroll a certificate with SSCEP? 

### ISSUE THREAD

**Issue by jrmejiaa** [certnanny/sscep#182]
Hi all, 

Imagine that I got my certificate according to the Steps in the README until the fourth step [Make Enrollment](https://github.com/certnanny/sscep?tab=readme-ov-file#step-4---make-enrollment). After a few days, I wanted to not longer allow this certificate and want to revoke from the system. The Step seven, shows how to look for the revocation list, but not how to revoke a certificate. 

It is this possible with the tool? 

Thanks for your time. 

Happy Coding

**Comment by mbartosch** [comment]
According to RFC 8894 Section 2.8 SCEP does not support revocation.
https://www.rfc-editor.org/rfc/rfc8894.html#name-certificate-revocation

**Comment by jrmejiaa** [comment]
Hi @mbartosch, yes you are right, I am a newbie in PKIs and SCEP and I thought that this process was triggered from the client. Thanks for the closing.
