### ISSUE TITLE
Error writing ca cert during getca

### ISSUE THREAD

**Issue by gyutani** [certnanny/sscep#22]
I'm looking at the develop branch:

git log -1
commit 039f9d29bf628130d43fb1eb05b732c80e5c4dc5
Merge: 0400cf4 f9beb16
Author: Andreas Leibl <andreas@leibl.co.uk>
Date:   Fri Dec 20 06:42:16 2013 -0800

    Merge pull request #20 from aleibl/develop

    Changed misleading filenames of AIX pre-/post-install scripts

I'm running on Ubuntu 12.04 64-bit although I don't think this is operating system specific.  On line 611 of sscep.c the line currently is:

if (PEM_write_X509(fp, c_char) != 1) {

I believe the second paramater of PEM_write_X509() is a X509* so I imagine the line probably was meant to be:

if (PEM_write_X509(fp, cacert) != 1) {

**Comment by codegeass82** [comment]
Hello,
I met this error too. So, I applied the patch which Gyutani mentioned(c_char -> cacert) and the error is disappeared. Do you have a plan to apply this patch someday?

Thanks.

**Comment by mbartosch** [comment]
Fixed via 529455
