### ISSUE TITLE
Reorganize RPM package names for sscep

### ISSUE THREAD

**Issue by mrscotty** [certnanny/sscep#25]
Currently, the RPMs are created from two separate spec files. It might be better to have just a single spec file like many other projects (e.g.: perl) do. In addition, the preferred package (sscep-static) could be renamed to 'sscep' and the other package could continue to be called 'sscep-dyn'.

**Comment by gotthardp** [comment]
The RPM package generation has been simplified in 6d03fb24e935c4a16653f7a2ed22d3a5ab712238. Now there is just one spec file as requested.
