### ISSUE TITLE
Error Verifying Signature during ENROLL operation

### ISSUE THREAD

**Issue by 3vad3r** [certnanny/sscep#31]
Im trying to enroll my CSR using sscep with NDES+ADCS. In the CA logs I can see that my CSR is signed by CA and Certificate is issued successfully.  But sscep is not able to extract the signed certificate from the NDES response.

 ./sscep enroll -f my_conf > debug_tongs.log
./sscep: error verifying signature
31760:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:rsa_pk1.c:100:
31760:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:fips_rsa_eay.c:748:
31760:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:pk7_doit.c:981:

**Comment by kothabhaskar** [comment]
Hi 3vad3r,

Can you please let us know how your above problem got fixed ?
We are also seeing similar issue in our setup.
Appreciate your inputs on this, Thanks in advance.

Regards,
Bhaskar

**Comment by kuromike0629** [comment]
+1

**Comment by mbartosch** [comment]
This error message indicates a RSA padding error which can have a huge number of reasons and which cannot be analyzed with the information provided.
