### ISSUE TITLE
Integrity check failure

### ISSUE THREAD

**Issue by glnetanel** [certnanny/sscep#39]
Hi,

I am trying to use SSCEP with Windows2008 server CA. (please note it is 2008 and not 2000)
I following instruction as define in the tutorial, i create a key and csr using mkrequest 
i also managed to get ca certificate when running
./sscep_dyn getca -f sscep.conf

however, when i am trying to enroll certificate i am getting the below error:

ute@UTE-LX-a01:~/netanel/sscep/sscepStable/sscep-masterupdates$ ./sscep_dyn  enroll -f sscep.conf
./sscep_dyn: Found private key ./local.key as file. If the engine can handle it, loading the file
./sscep_dyn: selfsigned certificate written as ./selfsigned.crt
./sscep_dyn: sending certificate request
./sscep_dyn: valid response from server
./sscep_dyn: reply transaction id: 6AD7A727B67BD2AF62298DAEF48D4D4A
./sscep_dyn: pkistatus: FAILURE
./sscep_dyn: reason: Integrity check failed

i know that others in my company manged to create certificate on this server (using proprietary code).

Any idea what I have done wrong ? (BTW, i am using the sscep-masterupdates branch, i had problem building the other two)

Thanks, Gal.

**Comment by gotthardp** [comment]
From v0.8.1 (6489e20578355681c5e84c23df5d8104ba6e9df3) the sscep client will support certificate auto-selection. One could specify `-c ./ca.crt` only and the client will try to load all ca.crt-0, ca.crt-1, ca.crt-2, etc. and determine which suits best for `-c` and `-e`. It is however still possible to set just `-c ./ca.crt-0` to preserve the old behaviour.
