### ISSUE TITLE
Recommend modification to sscep.c to support issuer CAs other than a self-signed Root CA.

### ISSUE THREAD

**Issue by tedescn** [certnanny/sscep#42]
We have recently downloaded and compiled version 20081211 of sscep.c  In testing we note that it is configured to issues certificates from a self-signed Root CA rather than an intermediate Issuing CA.

Can we recommend a change to the code base that will allow intermediate Issuing CAs to be supported?

For version 20081211 of sscep this would mean changing line 551 from “X509_get_issuer_name(cacert))) {“ to “X509_get_subject_name(cacert))) {“. 

Note we believe this to be a typo where issuer & subject names are identical values within a self-signed Root CA but would different values for an intermediate Issuing CA.

**Comment by tedescn** [comment]
See attached diff.patch which may be helpful?
[diff.patch.txt](https://github.com/certnanny/sscep/files/51216/diff.patch.txt)

**Comment by mbartosch** [comment]
I am confused. We have been using sscep with three level CA hierarchies without any problem here.
Could you describe how to reproduce the actual problem?

**Comment by tedescn** [comment]
Martin,

 

I suspect the difference here is between the use of Enterprise and Managed PKI SCEP responders?

 

An Enterprise SCEP responder typically stands up a single instance of SCEP responder on a unique URL per issuing CA, as a result an enterprise SCEP responder only receives SCEP traffic for a specific Issuing CA.

 

A Managed PKI SCEP responder typically stands up a single SCEP responder for all Issuing CAs under management; this may be 10’s or 100’s of Issuing CAs. The consequence here is a single server is processing all SCEP requests and allocating them to appropriate Issuing CA queues for processing. The differences first manifest themselves in the use of the MESSAGE value in the GetCACert message, where the use of MESSAGE  becomes mandatory to identify which Issuing CA should process the request.

 

WRT the use of the SSCEP client the CetCACert, GetCACaps, PKCSReq messages work for us regards our Managed PKI SCEP responder. However, within the GetCertInitial message we see the IssuerName of the self-signed Root CA and Issuing CA from the Issuing CA. This IssuerName in theory should be relative to the certificate to be issued and hence should be the SubjectName of the Issuing CA. The impact is the request for GetCertInitial is forwarded to the IssuerName identified in the GetCertInitial message, which is the Self-signed Root CA and not the Issuer CA, hence the certificate request remains issued but not picked-up. The SSCEP client receives a “failure” response.

I hope this description helps? 

 

For information our Managed PKI platform is based on the Symantec (VeriSign) technology.

 

Finally, I can also share the SCEP responder debug messages out of band. The issue here is if I anonymise the debug the audit / visibility of this problem is lost. 

 

Regards

Nigel Tedeschi

**Comment by mbartosch** [comment]
Thanks, that's very interesting and helpful indeed. In OpenXPKI (peer project) we have the possibility to set up as many SCEP servers as desired, even multiple SCEP servers per Issuing CA is possible. We make use of this feature very liberally. 
OpenXPKI also handles the case you described (running multiple CA hierarchies, possibly even managed PKIs, also supporting SCEP for them), but currently OpenXPKI does not support one single SCEP server serving multiple Issuing CAs.
It's simply a case we have not yet encountered.
We will have to think a bit about this and check the suggested patch, please give us a little time.

BTW, you might want to have a look at https://github.com/Javex/libscep - this is a client library implementing the SCEP protocol (instead of a command line tool). We are working together with the authors and are currently considering migrating CertNanny and OpenXPKI to libscep once we are sure it works properly.

**Comment by tedescn** [comment]
Martin,

Thanks for the review, consideration and feedback.

See attached an anonymised version of the SCEP responder trace that shows the Root CA identified in the GetCertInitial message rather than issuing CA. If it helps contact me and I’m happy to share the actual trace.

If you need additional input to support ongoing consideration, please don’t hesitate to request.

I will take a look at the Javex/libscep and share any issues with the authors.
[SCEP Responder Log - anonymised - Draft 1B.docx](https://github.com/certnanny/sscep/files/53944/SCEP.Responder.Log.-.anonymised.-.Draft.1B.docx)

Regards
Nigel Tedeschi

**Comment by mbartosch** [comment]
Thanks for the detailed description and rationale. I pulled in #52 which essentially contained the same fix as in your patch.
