### ISSUE TITLE
generalize the Linux Makefile for cross-compilation

### ISSUE THREAD

**Issue by redbrain17** [certnanny/sscep#47]
To cross-compile sscep for my ARM architecture I need to adapt the Linux/Makefile 

-CC     = gcc
+CC     = arm-v5te-linux-gnueabi-gcc

is there a way to generalize that for other architectures?

**Comment by gotthardp** [comment]
Since 69df7a3e737e1997f26e71208bb355dae5b2f126 we use GNU autotools that make the cross-compilation much simpler.
