### ISSUE TITLE
current develop segfaults on debian/ubuntu

### ISSUE THREAD

**Issue by oliwel** [certnanny/sscep#5]
The develop branch (currently in rad1us repo) segfaults during enrollment on debian 6 and ubuntu 13.04.

c37524d -> works
f481654/f654a22 -> dont build due to unmet references (windows stuff)?
b9618e8 -> segfaults

output of entrollment script
/home/oliwel/workspace/OpenXPKI/bulkenrollment/enrollrequests: Zeile 132: 29067 Speicherzugriffsfehler  (Speicherabzug geschrieben) /home/oliwel/workspace/OpenXPKI/sscep/sscep enroll -u http://x.x.x.x/cgi-bin/scep/scep -c /tmp/scepcacert-0 -r scep-spool/scep-signer.test.openxpki.org.req -k /tmp/key.vXdvWf -l scep-spool/scep-signer.test.openxpki.org-cert.pem -t 10 -n 1 > /dev/null 2>&1

with sctrace:
open("/tmp/scepcacert-0", O_RDONLY)     = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=1346, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1828b9a000
read(3, "-----BEGIN CERTIFICATE-----\nMIID"..., 4096) = 1346
close(3)                                = 0
munmap(0x7f1828b9a000, 4096)            = 0
--- SIGSEGV (Segmentation fault) @ 0 (0) ---

**Comment by gotthardp** [comment]
I guess this has been addressed already.
