### ISSUE TITLE
sscep getca failed with strange error

### ISSUE THREAD

**Issue by redbrain17** [certnanny/sscep#51]
Hello,

I observe a issue  on this cmd: 

sscep getca -f /etc/sscep.conf
sscep: Error in /etc/sscep.conf on line 22
3068937424:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:346:line 22

my sscep.conf is the default one, I only changed the SCEP Url  

URL of the SCEP server.
URL             http://192.168.1.100/cgi-bin/scep/scep

sscep getca -c cert -u http://192.168.1.100:80/cgi-bin/scep/scep
is working like expected.

some ideas?

**Comment by mrscotty** [comment]
Hi Oliver,

Please double-check the URL you supplied to ensure the IP address is correct (192.168.1.00 doesn't look correct).

Scott

**Comment by redbrain17** [comment]
sry, I corrected the typo in the IP Address. I still see the same error

**Comment by redbrain17** [comment]
I added in the sscep file on every config assignment a "=" sign instead of spaces

URL  http://localhost/cgi-bin/scep/scep
URL  =  http://localhost/cgi-bin/scep/scep

this fixed the problem above.
