### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by karthik-reddy123** [certnanny/sscep#53]
hi,

i have been trying to install sscep in my linux machine,as i got somany errors i coudnt install that on my machine.can anyone please help me with this ?...below are the errors which i got during installation...plz rply me asap.....thanks in advance....
engine.h:7:1: error: unknown type name ‘ENGINE’
 ENGINE _scep_engine_init(ENGINE *e);
 ^
engine.h:7:26: error: unknown type name ‘ENGINE’
 ENGINE *scep_engine_init(ENGINE *e);
                          ^
engine.h:8:1: error: unknown type name ‘ENGINE’
 ENGINE *scep_engine_load_dynamic(ENGINE *e);
 ^
engine.h:8:34: error: unknown type name ‘ENGINE’
 ENGINE *scep_engine_load_dynamic(ENGINE *e);
                                  ^
engine.h:9:28: error: unknown type name ‘EVP_PKEY’
 void sscep_engine_read_key(EVP_PKEY *_key, char _id, ENGINE *e);
                            ^
engine.h:9:54: error: unknown type name ‘ENGINE’
 void sscep_engine_read_key(EVP_PKEY *_key, char _id, ENGINE *e);
                                                      ^
engine.h:10:32: error: unknown type name ‘EVP_PKEY’
 void sscep_engine_read_key_old(EVP_PKEY *_key, char _id, ENGINE *e);
                                ^
engine.h:10:58: error: unknown type name ‘ENGINE’
 void sscep_engine_read_key_old(EVP_PKEY *_key, char _id, ENGINE *e);
                                                          ^
engine.h:11:32: error: unknown type name ‘EVP_PKEY’
 void sscep_engine_read_key_new(EVP_PKEY *_key, char _id, ENGINE *e);
                                ^
engine.h:11:58: error: unknown type name ‘ENGINE’
 void sscep_engine_read_key_new(EVP_PKEY *_key, char _id, ENGINE *e);
                                                          ^
engine.h:14:33: error: unknown type name ‘EVP_PKEY’
 void sscep_engine_read_key_capi(EVP_PKEY *_key, char _id, ENGINE *e, char *storename);
                                 ^
engine.h:14:59: error: unknown type name ‘ENGINE’
 void sscep_engine_read_key_capi(EVP_PKEY *_key, char _id, ENGINE *e, char *storename);
                                                           ^
sscep.c: In function ‘main’:
sscep.c:324:3: warning: implicit declaration of function ‘scep_engine_init’ [-Wimplicit-function-declaration]
   scep_t.e = scep_engine_init(scep_t.e);
   ^
sscep.c:324:12: warning: assignment makes pointer from integer without a cast [enabled by default]
   scep_t.e = scep_engine_init(scep_t.e);
            ^
sscep.c:612:4: warning: passing argument 2 of ‘PEM_write_X509’ from incompatible pointer type [enabled by default]
    if (PEM_write_X509(fp, c_char) != 1) {
    ^
In file included from sscep.h:60:0,
                 from sscep.c:11:
../openssl/include/openssl/pem.h:294:6: note: expected ‘struct X509 *’ but argument is of type ‘char *’
  int PEM_write_##name(FILE *fp, type *x);
      ^
../openssl/include/openssl/pem.h:323:2: note: in expansion of macro ‘DECLARE_PEM_write_fp’
  DECLARE_PEM_write_fp(name, type) 
  ^
../openssl/include/openssl/pem.h:335:2: note: in expansion of macro ‘DECLARE_PEM_write’
  DECLARE_PEM_write(name, type)
  ^
../openssl/include/openssl/pem.h:541:1: note: in expansion of macro ‘DECLARE_PEM_rw’
 DECLARE_PEM_rw(X509, X509)
 ^
sscep.c:688:27: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
      scep_t.reply_payload = reply.payload;
                           ^
sscep.c:776:5: warning: implicit declaration of function ‘sscep_engine_read_key_new’ [-Wimplicit-function-declaration]
     sscep_engine_read_key_new(&rsa, k_char, scep_t.e);
     ^
sscep.c:790:6: warning: implicit declaration of function ‘sscep_engine_read_key_old’ [-Wimplicit-function-declaration]
      sscep_engine_read_key_old(&renewal_key, K_char, scep_t.e);
      ^
sscep.c:79:8: warning: variable ‘p7’ set but not used [-Wunused-but-set-variable]
  PKCS7 p7;
        ^
make: *_\* [sscep.o] Error 1

**Comment by gotthardp** [comment]
The build system has been greatly improved since 2015, so I am closing this.
