### ISSUE TITLE
Scep: certificate issuance problem

### ISSUE THREAD

**Issue by forna76** [certnanny/sscep#60]
Hi all
I have a problem with the NDES, I cannot get a certificate. 

I use openscep client (on CentOS) to send a CSR to an Issuing CA (windows server 2012 R2) with NDES installed. 

From the command line I use the follwong:
./sscep_dyn enroll -v -u http://192.168.236.88/CertSrv/mscep/mscep.dll -k try -r try33.csr -l certificato.crt -c IntermediateCA2.cer

try is the key generated using openssl
try33.csr is the CSR needed to be signed
IntermediateCA2.cer is the Issuer CA certificate manually imported

Error on the client:
./sscep_dyn: wrong (or missing) MIME content type

Error on the Issuer CA side (event viewer):
"The Network Device Enrollment Service cannot decrypt the client's PKCS7 message (0x80090005).  Bad Data."

Does anyone has any idea about this issue or a hint about troubleshoot that?

Thanks
Cristian

**Comment by mbartosch** [comment]
Hi,

> From the command line I use the follwong:
> ./sscep_dyn enroll -v -u http://192.168.236.88/CertSrv/mscep/mscep.dll -k try -r try33.csr -l certificato.crt -c IntermediateCA2.cer

> Error on the Issuer CA side (event viewer):
> "The Network Device Enrollment Service cannot decrypt the client's PKCS7 message (0x80090005). Bad Data."
> 
> Does anyone has any idea about this issue or a hint about troubleshoot that?

Looks very much like the SCEP request was not encrypted with the correct certificate. You need to specify the SCEP RA certicate to the sscep command.

Sorry, no time for more details…

cheers

Martin

**Comment by forna76** [comment]
Hi Martin

Thanks for the answer. In the scep command I specifyed the CA server certificate, is that right?
I exported it using the mmc console and then copied it manually on the scep client machine...

Cristian

**Comment by gotthardp** [comment]
Similar to as #39, likely solved in 0.8.1 by 6489e20578355681c5e84c23df5d8104ba6e9df3.
