### ISSUE TITLE
sscep fails to build with sscep_dyn

### ISSUE THREAD

**Issue by sharbich** [certnanny/sscep#64]
Build process fails.
`gcc -Wall -O  -I ../openssl/include  -o sscep_static sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o ../openssl/libcrypto.a -ldl
gcc -Wall -O  -I ../openssl/include  -o sscep_dyn sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o -lcrypto -L../openssl
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): undefined reference to `dlopen'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x24): undefined reference to `dlsym'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x2f): undefined reference to `dlclose'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
(.text+0x324): undefined reference to `dlsym'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
(.text+0x3cb): undefined reference to `dlerror'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
(.text+0x444): undefined reference to `dlsym'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
(.text+0x4eb): undefined reference to `dlerror'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
(.text+0x559): undefined reference to `dlopen'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
(.text+0x5bb): undefined reference to `dlclose'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
(.text+0x5f3): undefined reference to `dlerror'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
(.text+0x68f): undefined reference to `dladdr'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
(.text+0x6f9): undefined reference to `dlerror'
../openssl/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
(.text+0x752): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
Makefile:26: recipe for target 'sscep_dyn' failed
make: *** [sscep_dyn] Error 1`
Can ear help me? Thank you very much for your support.
Stefan Harbich

**Comment by sharbich** [comment]
Hi all,
i can not compile all three versions (develop / master / masterupdate). I always get the same error message. My debian System is Jessie. I have openssl version 1.0.2g-1ubuntu4.5. Can not anyone help me how I compile the package?
Thanks for helping, Stefan Harbich

**Comment by sharbich** [comment]
Too bad that no one answers here

**Comment by rad1us** [comment]
Hi, 

it looks to me like you try to link a dynamic build vs. a Static openSSL build. Rebuild our openSSL and look that you don have only static libs .a but dynamic lib .so .

**Comment by sharbich** [comment]
Hi rad1us,
Can you give me a hint how I must compile openssl?
Thanks

**Comment by sharbich** [comment]
Hi rad1us,
i have compiled openssl
`./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic &&
make`
Compiler I now sscep again comes the same error message.
Thanks for a reply.

**Comment by sharbich** [comment]
Hi all,
it was my fault. After that I get the files `libcrypto.a
libcrypto.so` in the directory "openssl" are copied he build of sscep ran through.
Thanks for the replies and the help, by Stefan Harbich
