### ISSUE TITLE
Check sscep_static

### ISSUE THREAD

**Issue by sharbich** [certnanny/sscep#65]
Hi all,
Check if the service is working properly at all: `sscep_static getca -c tmp/cacert -u http://myhost/scep/scep` The following error message is displayed `./sscep_static: cannot open cert file for writing`. In the "sceep.log" the following error message is displayed  `2016/12/05 22:18:21 INFO:29793 Incoming request from 192.168.30.67 with
2016/12/05 22:18:38 DEBUG:29818 Starting logger from config with config /etc/openxpki/scep/log.conf, facility client.scep
2016/12/05 22:18:38 DEBUG:29818 Config for service scep loaded
2016/12/05 22:18:38 INFO:29818 SCEP handler initialized
2016/12/05 22:18:38 DEBUG:29818 Autodetect config file for service scep: %3Cany%20value%3E.conf
2016/12/05 22:18:38 DEBUG:29818 No config file found, falling back to default
` Since what seems to be wrong with the configuration file? Can you help me?
Thanks for replay, by Stefan Harbich

**Comment by gotthardp** [comment]
Hi. I am sorry for the delay-- I guess you solved the issue somehow anyway. I suspect this was because you were trying to store the certificates to `tmp/cacert` and the `tmp` directory either did not exist or was not writeable for the sscep tool.
