### ISSUE TITLE
engine pkcs11 usage creates Segmentation fault

### ISSUE THREAD

**Issue by viperomega** [certnanny/sscep#73]
Hi,
i try to use sscep with softhsm2 and p11-kit for pkcs11
sscep is compiled on a Ubuntu 17.10 with Makefile changed to use libssl-dev:amd64 1.0.2g-1ubuntu13.2  for static.

both dyn and static crash with  Segmentation fault

 

strace ./sscep_dyn enroll -u http://openxpki/scep/scep -k "pkcs11:token=lhm;object=802.1X;type=private" -r tmp/scep-test.csr     -c tmp/cacert-0     -l tmp/scep-test.crt     -t 10 -n 1 -v -g pkcs11

[12330.397793] sscep_dyn[4704]: segfault at 0 ip 000055d1b8b0102b sp 00007fff343ca9c0 error 4 in sscep_dyn[55d1b8af4000+12000]

strace (last part)
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 5), ...}) = 0
write(1, "./sscep_dyn: starting sscep, ver"..., 43./sscep_dyn: starting sscep, version 0.6.1
) = 43
write(1, "./sscep_dyn: new transaction\n", 29./sscep_dyn: new transaction
) = 29
write(1, "./sscep_dyn: transaction id: D41"..., 62./sscep_dyn: transaction id: D41D8CD98F00B204E9800998ECF8427E
) = 62
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320<\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=75248, ...}) = 0
mmap(NULL, 2170448, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f626d88c000
mprotect(0x7f626d89d000, 2093056, PROT_NONE) = 0
mmap(0x7f626da9c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7f626da9c000
close(3)                                = 0
mprotect(0x7f626da9c000, 4096, PROT_READ) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by viperomega** [comment]
Hi,
looks like segfault reason is missing "engine" MODULE_PATH.
Please enhance error handling.

**Comment by gotthardp** [comment]
Thanks. The error handling was recently significantly improved.
