### ISSUE TITLE
(FIXED) illegal size of payload in Redhat 7.5

### ISSUE THREAD

**Issue by yfng56** [certnanny/sscep#83]
I have been using sscep client with Windows 2012R2 NDES without any issue. The problem started when my client machine upgraded from Redhat 7.2 to 7.5. 
The sscep unable to enroll cert. In the pkcs7 message it has error illegal size of payload.

anyone can provide fix here will very much appreciated.

n8aeGXvDkeLEZOLFzHrZi77DPSDyBaxNR752Tz6S+ZaE/fGMeD+MUWnau45+Sud1
l7YnjiYMiPb7VOHh
**-----END PKCS7-----
sscep: applying base64 encoding
sscep: base64 encoded payload size: 3462 bytes
sscep: scep msg: GET /certsrv/mscep/mscep.dll/pkiclient.exe??**operation=PKIOperation&message=MIIJ%2BAYJKoZIhvcNAQcCoIIJ6TCCCeUCAQExDjAMBggqhkiG9w0CBQUAMIIE1gYJ%0AKoZIhvcNAQcBoIIExwSCBMMwggS/BgkqhkiG9w0BBwOgggSwMIIErAIBADGCAa8w%0AggGrAgEAMIGSMHsxEzARBgoJkiaJk/IsZAEZFgNjb20xEzARBgoJkiaJk/IsZAEZ%0AFgNkYnMx

OILbno/Gsscep: illegal size of payload

FIXED: I finally found solution and issue.
           There were two issues, I'm using Microsoft NDES which running on IIS. scep client sending the encoded base64 message to IIS has exceed the 2048 MaxQuery string of IIS. 
Solution: Increase the IIS MaxqueryString and MaxBytes
          Second issue was CSR generated by mkrequest is make used of openssl in OS level. Linux 7.5 has changed openssl standard. I add one line under [ req ] section. It works just fine.
[ req ]
string_mask = nombstr

**Comment by juresaht2** [comment]
For anyone else also trying to diagnose this issue:
```
[ req ]
string_mask = nombstr
```
...is to be added on line 114 of the mkrequest script.

Also keep in mind that using an expired challenge password will yield the same error.
