### ISSUE TITLE
Header file openssl/asn1_mac.h obsolete

### ISSUE THREAD

**Issue by bee-mere** [certnanny/sscep#85]
When trying to build sscep together with openssl 1.1.2 (the latest version available on Github as of today), the error message 

```
../openssl/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
```

occurs. What could be done to solve this? Is it just a configuration error on my side?

**Comment by subburamr** [comment]
I had the same error on Ubuntu 18.04, OpenSSL 1.1.0g
The compilation worked after I installed libssl1.0-dev

**Comment by gotthardp** [comment]
The deprecated asn1_mac isn't used since v0.7.0 (984a802774c5ddd3059124ae8b0834c2b65c5e04).
