### ISSUE TITLE
gcc: error: ../openssl/libcrypto.a: No such file or directory

### ISSUE THREAD

**Issue by ghost** [certnanny/sscep#87]
I am installing latest version of sscep (0.6.1) on Debian jessie 8.11 x64. 
libssl-dev is already installed on the machine.
./Configure runs fine but make gives following error 
gcc -Wall -O  -I ../openssl/include  -o sscep_static sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o ../openssl/libcrypto.a -ldl
gcc: error: ../openssl/libcrypto.a: No such file or directory
Makefile:23: recipe for target 'sscep_static' failed
make: *** [sscep_static] Error 1

**Comment by scottthomas007** [comment]
I am also facing the same issue. Someone help please.

**Comment by mbartosch** [comment]
The build script assumes that OpenSSL is unpacked, configured and compiled in ../openssl

Three ways to resolve this:
1. Unpack, configure and compile openssl in ../openssl
2. Only build the dynamic executable via
make sscep_dyn
3. Specify the location of the static library explicitly:
make OPENSSL=/usr/lib/x86_64-linux-gnu

The latter works with Debian Jessie.

**Comment by scottthomas007** [comment]
It works but the make install fails ....

**Comment by juresaht2** [comment]
For CentOS the suitable package is `openssl-static`. It is currently missing on CentOS 8: https://bugs.centos.org/view.php?id=17139
