### ISSUE TITLE
sscep_static compliation failure

### ISSUE THREAD

**Issue by maciejmalysz** [certnanny/sscep#88]
[mmalysz@orch-aaa-vm sscep]$ make
gcc -Wall -O  -I ../openssl/include  -o sscep_static sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o ../openssl/libcrypto.a -ldl
sscep.o: In function `main':
sscep.c:(.text+0x14bb): undefined reference to `sk_num'
sscep.c:(.text+0x1502): undefined reference to `sk_value'
sscep.c:(.text+0x1679): undefined reference to `sk_num'
sceputils.o: In function `init_scep':
sceputils.c:(.text+0x378): undefined reference to `OPENSSL_add_all_algorithms_noconf'
sceputils.c:(.text+0x37d): undefined reference to `ERR_load_crypto_strings'
pkcs7.o: In function `pkcs7_verify_unwrap':
pkcs7.c:(.text+0x27c): undefined reference to `sk_value'
pkcs7.o: In function `add_attribute_string':
pkcs7.c:(.text+0x5bd): undefined reference to `sk_push'
pkcs7.o: In function `add_attribute_octet':
pkcs7.c:(.text+0x670): undefined reference to `sk_push'
pkcs7.o: In function `pkcs7_wrap':
pkcs7.c:(.text+0xa15): undefined reference to `sk_new'
pkcs7.c:(.text+0xa68): undefined reference to `sk_push'
pkcs7.c:(.text+0xaae): undefined reference to `sk_push'
pkcs7.c:(.text+0xe44): undefined reference to `sk_new_null'
pkcs7.o: In function `get_attribute':
pkcs7.c:(.text+0x11b8): undefined reference to `sk_value'
pkcs7.c:(.text+0x11d8): undefined reference to `sk_num'
pkcs7.c:(.text+0x1217): undefined reference to `sk_value'
pkcs7.c:(.text+0x1225): undefined reference to `sk_num'
pkcs7.o: In function `pkcs7_unwrap':
pkcs7.c:(.text+0x1608): undefined reference to `sk_value'
ias.o: In function `d2i_pkcs7_issuer_and_subject':
ias.c:(.text+0x1b9): undefined reference to `asn1_add_error'
ias.c:(.text+0x1f4): undefined reference to `asn1_GetSequence'
ias.c:(.text+0x282): undefined reference to `asn1_const_Finish'
ias.c:(.text+0x2d5): undefined reference to `asn1_add_error'
fileutils.o: In function `write_crl':
fileutils.c:(.text+0x1b): undefined reference to `sk_value'
fileutils.o: In function `write_local_cert':
fileutils.c:(.text+0x168): undefined reference to `sk_num'
fileutils.c:(.text+0x18d): undefined reference to `sk_value'
fileutils.c:(.text+0x397): undefined reference to `sk_num'
fileutils.o: In function `write_other_cert':
fileutils.c:(.text+0x4ef): undefined reference to `sk_value'
fileutils.c:(.text+0x58c): undefined reference to `sk_num'
fileutils.o: In function `write_ca_ra':
fileutils.c:(.text+0x7b1): undefined reference to `sk_value'
fileutils.c:(.text+0xa4c): undefined reference to `sk_num'
configuration.o: In function `scep_conf_load':
configuration.c:(.text+0x1042): undefined reference to `sk_num'
configuration.c:(.text+0x109f): undefined reference to `sk_value'
engine.o: In function `sscep_engine_report_error':
engine.c:(.text+0x5): undefined reference to `ERR_load_crypto_strings'
engine.c:(.text+0x16): undefined reference to `ERR_free_strings'
engine.o: In function `scep_engine_init':
engine.c:(.text+0x29b): undefined reference to `ENGINE_load_dynamic'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x45): undefined reference to `pthread_rwlock_init'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_read_lock':
threads_pthread.c:(.text+0x85): undefined reference to `pthread_rwlock_rdlock'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_write_lock':
threads_pthread.c:(.text+0xa5): undefined reference to `pthread_rwlock_wrlock'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_unlock':
threads_pthread.c:(.text+0xc5): undefined reference to `pthread_rwlock_unlock'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_lock_free':
threads_pthread.c:(.text+0xea): undefined reference to `pthread_rwlock_destroy'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_run_once':
threads_pthread.c:(.text+0x115): undefined reference to `pthread_once'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_init_local':
threads_pthread.c:(.text+0x135): undefined reference to `pthread_key_create'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_set_local':
threads_pthread.c:(.text+0x167): undefined reference to `pthread_setspecific'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_cleanup_local':
threads_pthread.c:(.text+0x187): undefined reference to `pthread_key_delete'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `openssl_init_fork_handlers':
threads_pthread.c:(.text+0x1e3): undefined reference to `pthread_once'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_get_local':
threads_pthread.c:(.text+0x153): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status
make: *** [sscep_static] Error 1

**Comment by johnxpan** [comment]
Have the same compiling error on Ubuntu 16.04:
gcc -Wall -O  -I ../openssl/include  -o sscep_static sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o ../openssl/libcrypto.a -ldl
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x45): undefined reference to `pthread_rwlock_init'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_read_lock':
threads_pthread.c:(.text+0x85): undefined reference to `pthread_rwlock_rdlock'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_write_lock':
threads_pthread.c:(.text+0xa5): undefined reference to `pthread_rwlock_wrlock'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_unlock':
threads_pthread.c:(.text+0xc5): undefined reference to `pthread_rwlock_unlock'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_lock_free':
threads_pthread.c:(.text+0xea): undefined reference to `pthread_rwlock_destroy'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_run_once':
threads_pthread.c:(.text+0x115): undefined reference to `pthread_once'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_init_local':
threads_pthread.c:(.text+0x135): undefined reference to `pthread_key_create'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_set_local':
threads_pthread.c:(.text+0x167): undefined reference to `pthread_setspecific'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_cleanup_local':
threads_pthread.c:(.text+0x187): undefined reference to `pthread_key_delete'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `openssl_init_fork_handlers':
threads_pthread.c:(.text+0x1e3): undefined reference to `pthread_once'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
../openssl/libcrypto.a(libcrypto-lib-threads_pthread.o): In function `CRYPTO_THREAD_get_local':
threads_pthread.c:(.text+0x153): undefined reference to `pthread_getspecific'
sscep.o: In function `main':
sscep.c:(.text+0x15c4): undefined reference to `sk_num'
sscep.c:(.text+0x1616): undefined reference to `sk_value'
sscep.c:(.text+0x17c2): undefined reference to `sk_num'
sceputils.o: In function `init_scep':
sceputils.c:(.text+0x3e9): undefined reference to `OPENSSL_add_all_algorithms_noconf'
sceputils.c:(.text+0x3ee): undefined reference to `ERR_load_crypto_strings'
pkcs7.o: In function `pkcs7_verify_unwrap':
pkcs7.c:(.text+0x2bc): undefined reference to `sk_value'
pkcs7.o: In function `add_attribute_string':
pkcs7.c:(.text+0x656): undefined reference to `sk_push'
pkcs7.o: In function `add_attribute_octet':
pkcs7.c:(.text+0x713): undefined reference to `sk_push'
pkcs7.o: In function `pkcs7_wrap':
pkcs7.c:(.text+0xae2): undefined reference to `sk_new'
pkcs7.c:(.text+0xb3a): undefined reference to `sk_push'
pkcs7.c:(.text+0xb89): undefined reference to `sk_push'
pkcs7.c:(.text+0xf6d): undefined reference to `sk_new_null'
pkcs7.o: In function `get_attribute':
pkcs7.c:(.text+0x132b): undefined reference to `sk_value'
pkcs7.c:(.text+0x134b): undefined reference to `sk_num'
pkcs7.c:(.text+0x138f): undefined reference to `sk_value'
pkcs7.c:(.text+0x13a4): undefined reference to `sk_num'
pkcs7.o: In function `pkcs7_unwrap':
pkcs7.c:(.text+0x1822): undefined reference to `sk_value'
ias.o: In function `d2i_pkcs7_issuer_and_subject':
ias.c:(.text+0x1dd): undefined reference to `asn1_add_error'
ias.c:(.text+0x218): undefined reference to `asn1_GetSequence'
ias.c:(.text+0x2ac): undefined reference to `asn1_const_Finish'
ias.c:(.text+0x2ff): undefined reference to `asn1_add_error'
fileutils.o: In function `write_crl':
fileutils.c:(.text+0x1b): undefined reference to `sk_value'
fileutils.o: In function `write_local_cert':
fileutils.c:(.text+0x194): undefined reference to `sk_num'
fileutils.c:(.text+0x1be): undefined reference to `sk_value'
fileutils.c:(.text+0x3ef): undefined reference to `sk_num'
fileutils.o: In function `write_other_cert':
fileutils.c:(.text+0x586): undefined reference to `sk_value'
fileutils.c:(.text+0x62d): undefined reference to `sk_num'
fileutils.o: In function `write_ca_ra':
fileutils.c:(.text+0x8a3): undefined reference to `sk_value'
fileutils.c:(.text+0xb72): undefined reference to `sk_num'
configuration.o: In function `scep_conf_load':
configuration.c:(.text+0x10b6): undefined reference to `sk_num'
configuration.c:(.text+0x1118): undefined reference to `sk_value'
engine.o: In function `sscep_engine_report_error':
engine.c:(.text+0x5): undefined reference to `ERR_load_crypto_strings'
engine.c:(.text+0x16): undefined reference to `ERR_free_strings'
engine.o: In function `scep_engine_init':
engine.c:(.text+0x2cd): undefined reference to `ENGINE_load_dynamic'
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'sscep_static' failed
make: *** [sscep_static] Error 1

**Comment by gotthardp** [comment]
We migrated to autotools recently. That should improve the situation significantly.
