### ISSUE TITLE
 sscep build failure

### ISSUE THREAD

**Issue by happyfeet2018** [certnanny/sscep#92]
Hi,
I am geting following error  while compiling static scep 

gcc -Wall -O  -I ../openssl-1.0.2n/include  -o sscep_static sscep.o init.o net.o sceputils.o pkcs7.o ias.o fileutils.o configuration.o engine.o ../openssl-1.0.2n/libcrypto.a -ldl
/usr/bin/ld: ../openssl-1.0.2n/libcrypto.a(mem.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../openssl-1.0.2n/libcrypto.a(mem.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../openssl-1.0.2n/libcrypto.a(mem.o): Relocations in generic ELF (EM: 40)
../openssl-1.0.2n/libcrypto.a: could not read symbols: File in wrong format

Thanks

**Comment by aleibl** [comment]
Hi,

Could you provide some context, please? OS, versions and so on ... like:

uname -a
cat /etc/os-release (or whatever is appropriate for your distro)
ggc --version

and so on?

**Comment by happyfeet2018** [comment]
Hi ,

Below is the information: 

I am using openssl-1.0.2n that is compiled using arm-wrs-linux-gnueabi-armv6jel-glibc_small-gcc.
Only modified the path of openssl in makefile.

cat /etc/os-release :
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

gcc --version :
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

uname -a :
Linux aquabld 3.13.0-65-generic #106~precise1-Ubuntu SMP Fri Oct 2 22:06:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks for help ..

**Comment by happyfeet2018** [comment]
Also I am able to build sscep_dyn  this issue is specifically for sscep_static ...   when it is trying to include 
libcrypto.a it says File in wrong format.

**Comment by gotthardp** [comment]
We migrated to autotools recently. That should improve the situation significantly.
