### ISSUE TITLE
undefined reference to `dlopen'

### ISSUE THREAD

**Issue by xnandersson** [certnanny/sscep#93]
...can be fixed by adding "-ldl" to Makefile

...
LDLIBS = -lcrypto -ldl
...

on Ubuntu 18.04

**Comment by xnandersson** [comment]
Dockerfile
-------------
FROM ubuntu:bionic
RUN apt-get update && apt-get install -y build-essential libssl1.0-dev
#
# OpenSSL 1.0.2
#
WORKDIR /root
ADD https://github.com/openssl/openssl/archive/OpenSSL_1_0_2s.tar.gz .
RUN tar -xf OpenSSL_1_0_2s.tar.gz
RUN ln -s openssl-OpenSSL_1_0_2s/ openssl
WORKDIR /root/openssl
RUN ./config && make
#
# SSCEP
#
WORKDIR /root
COPY Makefile.patch /root
ADD https://github.com/certnanny/sscep/archive/v0.6.1.tar.gz .
# sscep-0.6.1
RUN tar -xf v0.6.1.tar.gz
WORKDIR /root/sscep-0.6.1/Linux
RUN patch Makefile /root/Makefile.patch
WORKDIR /root/sscep-0.6.1
RUN ./Configure && make
RUN cp sscep_dyn sscep_static /usr/local/bin


Makefile.patch
-------------------
--- Makefile	2019-07-31 15:28:09.921761233 +0200
+++ Makefile.new	2019-07-31 15:28:42.661761233 +0200
@@ -11,7 +11,7 @@
 CFLAGS	= -Wall -O $(WITH_DEBUG) -I $(OPENSSL)/include 
 
 LDFLAGS = -L$(OPENSSL)
-LDLIBS = -lcrypto
+LDLIBS = -lcrypto -ldl
 
 MAN	= sscep.8
 PROG	= sscep

**Comment by gotthardp** [comment]
Thanks for the Dockerfile.
We have switched to GNU autotools recently, which (hopefully) addresses also this issue.
